package(default_visibility = ["//:internal"])

load("//:defs.bzl", "<%- mainBazelTarget %>")

<%- mainBazelTarget %>(
    deps = [
        # "@gs_tools//src",
        # "@gs_ui//src",
        # "//src/data",
    ])